In [ ]:
from sklearn.ensemble import StackingClassifier, StackingRegressor, BaggingRegressor, BaggingClassifier, GradientBoostingRegressor,GradientBoostingClassifier, RandomForestClassifier, RandomForestRegressor
from sklearn.svm import LinearSVC
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv("balanced_bank_preprocessed.csv") 

In [ ]:
df1.drop(df1.columns[0], axis = 1, inplace = True)
df1.head()

job_cl  marital_cl  education_cl  default_cl  housing_cl  loan_cl  \
0 34579       0           1             0           0           0        0   
1 446         2           0             3           0           1        0   
2 20173       0           0             0           0           1        0   
3 18171       0           0             1           0           0        1   
4 30128       4           1             0           0           0        0   

         contact_cl  month_cl  day_of_week_cl  duration  campaign  pdays  \
0 34579           0         2               3       143         1    999   
1 446             1         2               1      1623         1    999   
2 20173           0         5               0       610         2    999   
3 18171           1         4               2      1089         2    999   
4 30128           0         1               3       211         1    999   

         previous  poutcome_cl  emp.var.rate  cons.price.idx  cons.conf.idx  \
0 34579         1            1          -1.8          92.893          -46.2   
1 446           0            0           1.1          93.994          -36.4   
2 20173         0            0           1.4          93.444          -36.1   
3 18171         0            0           1.4          93.918          -42.7   
4 30128         0            0          -1.8          93.075          -47.1   

         euribor3m  nr.employed  y_cl  
0 34579      1.266       5099.1     0  
1 446        4.857       5191.0     1  
2 20173      4.965       5228.1     1  
3 18171      4.963       5228.1     1  
4 30128      1.365       5099.1     0

In [ ]:
df1.info() 

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9280 entries, (0, 34579) to (9279, 16807)
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   job_cl          9280 non-null   int64  
 1   marital_cl      9280 non-null   int64  
 2   education_cl    9280 non-null   int64  
 3   default_cl      9280 non-null   int64  
 4   housing_cl      9280 non-null   int64  
 5   loan_cl         9280 non-null   int64  
 6   contact_cl      9280 non-null   int64  
 7   month_cl        9280 non-null   int64  
 8   day_of_week_cl  9280 non-null   int64  
 9   duration        9280 non-null   int64  
 10  campaign        9280 non-null   int64  
 11  pdays           9280 non-null   int64  
 12  previous        9280 non-null   int64  
 13  poutcome_cl     9280 non-null   int64  
 14  emp.var.rate    9280 non-null   float64
 15  cons.price.idx  9280 non-null   float64
 16  cons.conf.idx   9280 non-null   float64
 17  euribor3m      

In [ ]:
X = df1.iloc[:, :-1].values
y = df1.iloc[:, 19].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
clf = BaggingClassifier()
clf.fit(X_train, y_train)

BaggingClassifier()

In [ ]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[1024  160]
 [ 157  979]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.87      1184
           1       0.86      0.86      0.86      1136

    accuracy                           0.86      2320
   macro avg       0.86      0.86      0.86      2320
weighted avg       0.86      0.86      0.86      2320

0.8633620689655173


In [ ]:
X_ = df1.iloc[:, :-2].values
y_ = df1.iloc[:, 18].values #квартальный показатель

In [ ]:
from sklearn.ensemble import BaggingRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [ ]:
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(X_, y_, test_size=0.25)

In [ ]:
from sklearn.model_selection import learning_curve 
from sklearn.metrics import make_scorer
from sklearn.linear_model import Lasso, Ridge, LassoCV, LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

reg = BaggingRegressor()
reg.fit(X_reg_train, y_reg_train)
y_reg_pred = reg.predict(X_reg_test)
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

MSE:  0.0009441379310362466
RMSE: 0.03072682754591249
MAE:  0.00063793106027929
R2:  0.9999998750298472


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [ ]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 992  192]
 [  89 1047]]
              precision    recall  f1-score   support

           0       0.92      0.84      0.88      1184
           1       0.85      0.92      0.88      1136

    accuracy                           0.88      2320
   macro avg       0.88      0.88      0.88      2320
weighted avg       0.88      0.88      0.88      2320

0.8788793103448276


In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
reg = GradientBoostingRegressor()
reg.fit(X_reg_train, y_reg_train)
y_reg_pred = reg.predict(X_reg_test)
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

MSE:  0.062049087012476856
RMSE: 0.24909654155061417
MAE:  0.05697150562777967
R2:  0.9999917869162693


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.pipeline import make_pipeline

In [ ]:
base_learners = [
                 ('rf_1', RandomForestClassifier(n_estimators=10, random_state=42)),
                 ('rf_2', LogisticRegression())             
                ]
clf = StackingClassifier(estimators=base_learners,
                         final_estimator=LogisticRegression(),  
                         cv=10)
clf.fit(X_train, y_train)

StackingClassifier(cv=10,
                   estimators=[('rf_1',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=42)),
                               ('rf_2', LogisticRegression())],
                   final_estimator=LogisticRegression())

In [ ]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[1004  180]
 [ 116 1020]]
              precision    recall  f1-score   support

           0       0.90      0.85      0.87      1184
           1       0.85      0.90      0.87      1136

    accuracy                           0.87      2320
   macro avg       0.87      0.87      0.87      2320
weighted avg       0.87      0.87      0.87      2320

0.8724137931034482


In [ ]:
from sklearn.ensemble import StackingRegressor

In [ ]:
base_learners = [
    ('rf', RandomForestRegressor(n_estimators=10, random_state=42)),
    ('svr', make_pipeline(StandardScaler(), LinearRegression()))]

clf = StackingRegressor(estimators = base_learners)
clf.fit(X_reg_train, y_reg_train)
y_reg_pred = reg.predict(X_reg_test)
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

MSE:  0.062049087012476856
RMSE: 0.24909654155061417
MAE:  0.05697150562777967
R2:  0.9999917869162693


In [ ]:
!pip install catboost
!pip install ipywidgets
from catboost import * 
from catboost import datasets

     |████████████████████████████████| 76.6 MB 1.2 MB/s 


In [ ]:
from catboost import CatBoostClassifier

#установка параметров
model = CatBoostClassifier (
    task_type = "CPU",
    iterations = 200,
    learning_rate = 0.1,
    use_best_model = True,
    loss_function = "CrossEntropy"
)

model.fit (
    X_train, y_train,
    eval_set = (X_test, y_test),
    verbose = 30,
    plot = True
)

y_pred = model.predict(X_test)
print(model.score(X_test, y_test))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.5957722	test: 0.5955455	best: 0.5955455 (0)	total: 50.5ms	remaining: 10s
30:	learn: 0.2741745	test: 0.2975468	best: 0.2975468 (30)	total: 154ms	remaining: 840ms
60:	learn: 0.2494112	test: 0.2863406	best: 0.2863406 (60)	total: 265ms	remaining: 603ms
90:	learn: 0.2350867	test: 0.2812326	best: 0.2812326 (90)	total: 381ms	remaining: 456ms
120:	learn: 0.2195411	test: 0.2771401	best: 0.2770700 (119)	total: 593ms	remaining: 387ms
150:	learn: 0.2071426	test: 0.2766512	best: 0.2766512 (150)	total: 930ms	remaining: 302ms
180:	learn: 0.1969893	test: 0.2763034	best: 0.2759529 (168)	total: 1.16s	remaining: 122ms
199:	learn: 0.1905708	test: 0.2768243	best: 0.2759529 (168)	total: 1.23s	remaining: 0us

bestTest = 0.2759529165
bestIteration = 168

Shrink model to first 169 iterations.
0.8875


In [ ]:
from catboost import CatBoostRegressor

model = CatBoostRegressor (
    task_type = "CPU",
    learning_rate = 0.1,
    use_best_model = True,
    loss_function = "RMSE"
)

model.fit (
    X_reg_train, y_reg_train,
    eval_set = (X_reg_test, y_reg_test),
    verbose = False,
    plot = True
)

y_reg_pred = model.predict(X_reg_test)
print(model.score(X_reg_test, y_reg_test))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0.9999892313503438


In [ ]:
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

MSE:  0.08135615092193477
RMSE: 0.2852299965325084
MAE:  0.0723459383885703
R2:  0.9999892313503438
